### ISSUE TITLE
Dataset Preparation

### ISSUE THREAD

**Issue by xing0047** [ChengHan111/E2VPT#1]
Dear Author,

Congrats on the ICCV acceptance and thanks for contributing your work to the community!

May I ask when will you release a compiled version of FGVC and VTAB-1k? Would be really appreciate it if you could further include this in the repo.

Many thanks again for your contribution.

**Comment by ChengHan111** [comment]
Hi, Thanks for your interests to our work! 
I am thinking about a possible release date after the DDL of ICLR2024, depending on my current workload. Thanks.

**Comment by xing0047** [comment]
Thanks for your kind reply. Understand. I will see if i can solve this by myself.

**Comment by WangYZ1608** [comment]
Congratulations. 
Will VTAB-1k be released soon?
