### ISSUE TITLE
Question on code implementation of calculate_importance

### ISSUE THREAD

**Issue by JH-GEECS** [ChengHan111/E2VPT#4]
Dear Cheng Han,

I have greatly appreciated the work you've done on this project.
I am writing to bring to your attention an issue I've encountered with calculating importance scores.

In trainer.py, the importance score is calculated as soft_tokens_importance += prompt_model.enc.transformer.prompt_soft_tokens_mask_cls_token.grad.
However, according to the formula (6) in the paper, it seems that it should be taken the absolute value for each data batch, which it wasn't, so it seems that this will result in a zero sum.
Can you confirm this?

Thank you for taking the time to read this issue. I understand the demands on your time and truly appreciate any guidance you can provide on this matter. Please let me know if there is any additional information I can supply to help resolve this.

Best regards,
jiho choi

**Comment by ChengHan111** [comment]
Please follow the implementation from the paper, like I said, the code is still in progress so there might be some bugs here and there. Thanks!
